import type {
  User,
  Startup,
  Conversation,
  Message,
  Notification,
  JoinRequest,
} from "@/lib/types";

/**
 * Initial dataset loaded into the store on first run. Akshay is the demo
 * account (founder of XYZ corp.) that the Replit prototype is built around.
 */

export const seedUsers: User[] = [
  {
    id: "u-akshay",
    email: "akshaycrln@gmail.com",
    password: "password",
    role: "founder",
    createdAt: 1_700_000_000_000,
    name: "Akshay",
    avatarColor: "bg-primary/20 text-primary",
    location: "Bengaluru, India",
    bio: "Founder building Crewboot — helping founders find serious co-founders, teams, and the knowledge to move fast.",
    skills: ["Product", "Vision", "Fundraising", "Leadership"],
    experience: "2x founder. 4 years building early-stage products.",
    linkedin: "https://linkedin.com/in/akshay",
    portfolio: "https://akshay.dev",
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-jordan",
    email: "jordan@xyz.co",
    password: "password",
    role: "team_member",
    createdAt: 1_700_100_000_000,
    name: "Jordan Kim",
    avatarColor: "bg-blue-500/20 text-blue-400",
    location: "Seoul, South Korea",
    bio: "CTO. Distributed systems and developer tooling. I like shipping.",
    skills: ["TypeScript", "Go", "Infrastructure", "System Design"],
    experience: "Ex-staff engineer. Built CI/CD platforms at scale.",
    linkedin: "https://linkedin.com/in/jordankim",
    portfolio: "https://github.com/jordankim",
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-mia",
    email: "mia@xyz.co",
    password: "password",
    role: "team_member",
    createdAt: 1_700_200_000_000,
    name: "Mia Torres",
    avatarColor: "bg-purple-500/20 text-purple-300",
    location: "Lisbon, Portugal",
    bio: "Head of Design. I care about clarity and momentum over pixels for their own sake.",
    skills: ["Product Design", "Design Systems", "Branding", "Figma"],
    experience: "Led design at two seed-stage startups.",
    linkedin: "https://linkedin.com/in/miatorres",
    portfolio: "https://dribbble.com/miatorres",
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-liam",
    email: "liam@xyz.co",
    password: "password",
    role: "team_member",
    createdAt: 1_700_300_000_000,
    name: "Liam Chen",
    avatarColor: "bg-emerald-500/20 text-emerald-400",
    location: "Singapore",
    bio: "Growth Lead. SEO, lifecycle, and referral loops.",
    skills: ["Growth", "SEO", "Lifecycle Marketing", "Analytics"],
    experience: "Scaled two B2B SaaS funnels from zero.",
    linkedin: "https://linkedin.com/in/liamchen",
    portfolio: "https://liamchen.co",
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-sarah",
    email: "sarah@sequoia.com",
    password: "password",
    role: "investor",
    createdAt: 1_700_400_000_000,
    name: "Sarah Chen",
    avatarColor: "bg-amber-500/20 text-amber-400",
    location: "San Francisco, CA",
    bio: "Partner at Sequoia. Former founder. Backed 40+ SaaS and AI companies.",
    skills: ["SaaS", "AI", "Seed", "Series A"],
    experience: "Partner @ Sequoia Capital. Check size $500K–$3M.",
    linkedin: "https://linkedin.com/in/sarahchen",
    portfolio: "https://sequoiacap.com",
  },
  {
    id: "u-david",
    email: "david@yc.com",
    password: "password",
    role: "mentor",
    createdAt: 1_700_500_000_000,
    name: "David Park",
    avatarColor: "bg-orange-500/20 text-orange-400",
    location: "San Francisco, CA",
    bio: "YC Group Partner. I help founders solve their own problem first.",
    skills: ["Fintech", "Fundraising", "Go-to-market", "Mentoring"],
    experience: "Partner @ Y Combinator. Mentored 100+ founders.",
    linkedin: "https://linkedin.com/in/davidpark",
    portfolio: "https://ycombinator.com",
  },
  {
    id: "u-aisha",
    email: "aisha@designco.com",
    password: "password",
    role: "service_provider",
    createdAt: 1_700_600_000_000,
    name: "Aisha Patel",
    avatarColor: "bg-pink-500/20 text-pink-400",
    location: "London, UK",
    bio: "Fractional brand & product design studio for early-stage startups.",
    skills: ["Branding", "Web Design", "Webflow", "Product Design"],
    experience: "Run a 4-person studio. 30+ startup launches.",
    linkedin: "https://linkedin.com/in/aishapatel",
    portfolio: "https://aishastudio.com",
  },
  {
    id: "u-tom",
    email: "tom@founder.io",
    password: "password",
    role: "founder",
    createdAt: 1_700_700_000_000,
    name: "Tom Nakamura",
    avatarColor: "bg-cyan-500/20 text-cyan-400",
    location: "Tokyo, Japan",
    bio: "Building a marketplace for local services. Looking for a technical co-founder.",
    skills: ["Marketplaces", "Operations", "Sales"],
    experience: "Second-time founder. Previously exited a logistics startup.",
    linkedin: "https://linkedin.com/in/tomnakamura",
    portfolio: "https://tomn.io",
    startupId: "s-machi",
    canJoinOthers: false,
  },
];

export const seedStartups: Startup[] = [
  {
    id: "s-xyz",
    ownerId: "u-akshay",
    name: "XYZ corp.",
    industry: "Productivity / SaaS",
    description:
      "An operating system for founders — bringing team, fundraising, and learning into one place.",
    stage: "Seed",
    website: "https://xyz.co",
    teamSize: 4,
    openRoles: [
      {
        id: "r-1",
        title: "Founding Backend Engineer",
        description: "Own the API and data layer. TypeScript/Node, Postgres.",
      },
      {
        id: "r-2",
        title: "Content & Community Lead",
        description: "Grow our founder community and learning content.",
      },
    ],
    createdAt: 1_700_000_000_000,
  },
  {
    id: "s-machi",
    ownerId: "u-tom",
    name: "Machi",
    industry: "Marketplace",
    description:
      "A hyperlocal marketplace connecting neighborhoods with trusted local service providers.",
    stage: "Pre-Seed",
    website: "https://machi.io",
    teamSize: 1,
    openRoles: [
      {
        id: "r-3",
        title: "Technical Co-Founder",
        description: "Lead all of engineering. Equity-heavy founding role.",
      },
    ],
    createdAt: 1_700_700_000_000,
  },
];

export const seedConversations: Conversation[] = [
  {
    id: "c-akshay-sarah",
    participantIds: ["u-akshay", "u-sarah"],
    createdAt: 1_701_000_000_000,
  },
  {
    id: "c-akshay-david",
    participantIds: ["u-akshay", "u-david"],
    createdAt: 1_701_100_000_000,
  },
];

export const seedMessages: Message[] = [
  {
    id: "m-1",
    conversationId: "c-akshay-sarah",
    senderId: "u-sarah",
    content:
      "Hi Akshay — saw XYZ corp. on Discover. The founder-tooling angle is interesting. What's your traction so far?",
    timestamp: 1_701_000_100_000,
  },
  {
    id: "m-2",
    conversationId: "c-akshay-sarah",
    senderId: "u-akshay",
    content:
      "Thanks Sarah! Early but promising — a few hundred founders on the waitlist and strong weekly retention on the dashboard.",
    timestamp: 1_701_000_200_000,
  },
  {
    id: "m-3",
    conversationId: "c-akshay-david",
    senderId: "u-david",
    content: "Happy to do office hours this week if useful. How's the team coming together?",
    timestamp: 1_701_100_100_000,
  },
];

export const seedJoinRequests: JoinRequest[] = [];

export const seedNotifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-akshay",
    type: "message",
    title: "New message from Sarah Chen",
    body: "Hi Akshay — saw XYZ corp. on Discover...",
    read: false,
    href: "/messages?c=c-akshay-sarah",
    timestamp: 1_701_000_100_000,
  },
  {
    id: "n-2",
    userId: "u-akshay",
    type: "system",
    title: "Complete your profile to stand out",
    body: "Startups with a full profile and skills get 3x more connection requests.",
    read: false,
    href: "/profile",
    timestamp: 1_701_050_000_000,
  },
  {
    id: "n-3",
    userId: "u-akshay",
    type: "message",
    title: "New message from David Park",
    body: "Happy to do office hours this week if useful...",
    read: true,
    href: "/messages?c=c-akshay-david",
    timestamp: 1_701_100_100_000,
  },
];
