import type {
  User,
  Startup,
  Conversation,
  Message,
  Notification,
  JoinRequest,
  ProjectTask,
} from "@/lib/types";

/**
 * Initial dataset loaded into the store on first run. Akshay is the demo
 * account (founder of XYZ corp.) that the Replit prototype is built around.
 */

export const seedUsers: User[] = [
  {
    id: "u-akshay",
    email: "akshaycrln@gmail.com",
    password: "password",
    role: "founder",
    createdAt: 1_700_000_000_000,
    name: "Akshay",
    avatarColor: "bg-primary/20 text-primary",
    location: "Bengaluru, India",
    bio: "Founder building Crewboot — helping founders find serious co-founders, teams, and the knowledge to move fast.",
    skills: ["Product", "Vision", "Fundraising", "Leadership"],
    experience: "2x founder. 4 years building early-stage products.",
    linkedin: "https://linkedin.com/in/akshay",
    portfolio: "https://akshay.dev",
    availability: "Full-time",
    interests: ["SaaS", "AI / ML", "Productivity"],
    onboarded: true,
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-jordan",
    email: "jordan@xyz.co",
    password: "password",
    role: "team_member",
    createdAt: 1_700_100_000_000,
    name: "Jordan Kim",
    avatarColor: "bg-blue-500/20 text-blue-400",
    location: "Seoul, South Korea",
    bio: "CTO. Distributed systems and developer tooling. I like shipping.",
    skills: ["TypeScript", "Go", "Infrastructure", "System Design"],
    experience: "Ex-staff engineer. Built CI/CD platforms at scale.",
    linkedin: "https://linkedin.com/in/jordankim",
    portfolio: "https://github.com/jordankim",
    availability: "Full-time",
    interests: ["Developer Tools", "SaaS", "AI / ML"],
    onboarded: true,
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-mia",
    email: "mia@xyz.co",
    password: "password",
    role: "team_member",
    createdAt: 1_700_200_000_000,
    name: "Mia Torres",
    avatarColor: "bg-purple-500/20 text-purple-300",
    location: "Lisbon, Portugal",
    bio: "Head of Design. I care about clarity and momentum over pixels for their own sake.",
    skills: ["Product Design", "Design Systems", "Branding", "Figma"],
    experience: "Led design at two seed-stage startups.",
    linkedin: "https://linkedin.com/in/miatorres",
    portfolio: "https://dribbble.com/miatorres",
    availability: "Full-time",
    interests: ["Consumer", "SaaS", "Productivity"],
    onboarded: true,
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-liam",
    email: "liam@xyz.co",
    password: "password",
    role: "team_member",
    createdAt: 1_700_300_000_000,
    name: "Liam Chen",
    avatarColor: "bg-emerald-500/20 text-emerald-400",
    location: "Singapore",
    bio: "Growth Lead. SEO, lifecycle, and referral loops.",
    skills: ["Growth", "SEO", "Lifecycle Marketing", "Analytics"],
    experience: "Scaled two B2B SaaS funnels from zero.",
    linkedin: "https://linkedin.com/in/liamchen",
    portfolio: "https://liamchen.co",
    availability: "Full-time",
    interests: ["Growth", "SaaS", "E-commerce"],
    onboarded: true,
    startupId: "s-xyz",
    canJoinOthers: false,
  },
  {
    id: "u-sarah",
    email: "sarah@sequoia.com",
    password: "password",
    role: "investor",
    createdAt: 1_700_400_000_000,
    name: "Sarah Chen",
    avatarColor: "bg-amber-500/20 text-amber-400",
    location: "San Francisco, CA",
    bio: "Partner at Sequoia. Former founder. Backed 40+ SaaS and AI companies.",
    skills: ["SaaS", "AI", "Seed", "Series A"],
    experience: "Partner @ Sequoia Capital. Check size $500K–$3M.",
    linkedin: "https://linkedin.com/in/sarahchen",
    portfolio: "https://sequoiacap.com",
    availability: "Part-time",
    interests: ["SaaS", "AI / ML", "Fintech"],
    onboarded: true,
  },
  {
    id: "u-david",
    email: "david@yc.com",
    password: "password",
    role: "mentor",
    createdAt: 1_700_500_000_000,
    name: "David Park",
    avatarColor: "bg-orange-500/20 text-orange-400",
    location: "San Francisco, CA",
    bio: "YC Group Partner. I help founders solve their own problem first.",
    skills: ["Fintech", "Fundraising", "Go-to-market", "Mentoring"],
    experience: "Partner @ Y Combinator. Mentored 100+ founders.",
    linkedin: "https://linkedin.com/in/davidpark",
    portfolio: "https://ycombinator.com",
    availability: "Weekends",
    interests: ["Fintech", "Fundraising", "Consumer"],
    onboarded: true,
  },
  {
    id: "u-aisha",
    email: "aisha@designco.com",
    password: "password",
    role: "service_provider",
    createdAt: 1_700_600_000_000,
    name: "Aisha Patel",
    avatarColor: "bg-pink-500/20 text-pink-400",
    location: "London, UK",
    bio: "Fractional brand & product design studio for early-stage startups.",
    skills: ["Branding", "Web Design", "Webflow", "Product Design"],
    experience: "Run a 4-person studio. 30+ startup launches.",
    linkedin: "https://linkedin.com/in/aishapatel",
    portfolio: "https://aishastudio.com",
    availability: "Part-time",
    interests: ["Consumer", "E-commerce", "SaaS"],
    onboarded: true,
  },
  {
    id: "u-tom",
    email: "tom@founder.io",
    password: "password",
    role: "founder",
    createdAt: 1_700_700_000_000,
    name: "Tom Nakamura",
    avatarColor: "bg-cyan-500/20 text-cyan-400",
    location: "Tokyo, Japan",
    bio: "Building a marketplace for local services. Looking for a technical co-founder.",
    skills: ["Marketplaces", "Operations", "Sales"],
    experience: "Second-time founder. Previously exited a logistics startup.",
    linkedin: "https://linkedin.com/in/tomnakamura",
    portfolio: "https://tomn.io",
    availability: "Full-time",
    interests: ["Marketplace", "Consumer", "Operations"],
    onboarded: true,
    startupId: "s-machi",
    canJoinOthers: false,
  },
  {
    id: "u-priya",
    email: "priya@dev.io",
    password: "password",
    role: "team_member",
    createdAt: 1_700_800_000_000,
    name: "Priya Sharma",
    avatarColor: "bg-rose-500/20 text-rose-400",
    location: "Bengaluru, India",
    bio: "Frontend engineer. Next.js, React, TypeScript, Tailwind. I obsess over fast, accessible, responsive UI and clean component design.",
    skills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "UI/UX"],
    experience: "4 years building product UIs at two seed-stage SaaS startups.",
    linkedin: "https://linkedin.com/in/priyasharma",
    portfolio: "https://priya.dev",
    availability: "Full-time",
    interests: ["SaaS", "Developer Tools", "Productivity"],
    onboarded: true,
  },
  {
    id: "u-marco",
    email: "marco@dev.io",
    password: "password",
    role: "team_member",
    createdAt: 1_700_850_000_000,
    name: "Marco Rossi",
    avatarColor: "bg-teal-500/20 text-teal-300",
    location: "Berlin, Germany",
    bio: "Full-stack leaning frontend. Love design systems and shipping polished products quickly.",
    skills: ["React", "TypeScript", "Node", "Design Systems"],
    experience: "3 years across two startups, last one acquired.",
    linkedin: "https://linkedin.com/in/marcorossi",
    portfolio: "https://marcorossi.dev",
    availability: "Part-time",
    interests: ["SaaS", "Consumer", "Web3"],
    onboarded: true,
  },
];

export const seedStartups: Startup[] = [
  {
    id: "s-xyz",
    ownerId: "u-akshay",
    name: "Crewboot",
    industry: "Productivity / SaaS",
    description:
      "Crewboot is the operating system for early-stage founders. We bring the four things a founder juggles every week — building the right team, talking to investors, learning fast, and getting AI guidance — into one focused home, so you spend less time switching between spreadsheets, CRMs, and bookmarks and more time moving your company forward. Today we help founders find serious co-founders and teammates, run a lightweight task board, track an investor pipeline, and get an AI copilot that actually knows their context.",
    stage: "Seed",
    website: "https://crewboot.co",
    teamSize: 4,
    memberRoles: {
      "u-akshay": "Founder & CEO",
      "u-jordan": "CTO",
      "u-mia": "Head of Design",
      "u-liam": "Growth Lead",
    },
    openRoles: [
      {
        id: "r-frontend",
        title: "Frontend Developer",
        description:
          "Own the Crewboot web app end to end. You'll build the founder dashboard, discovery, messaging, and recruitment surfaces in Next.js 14 (App Router), React, TypeScript, and Tailwind — shipping fast, polished, responsive UI that works on every device. You care about UX details, design-system consistency, and clean, reusable components. Bonus: an eye for product and motion. This is a founding-team role with real ownership and equity.",
      },
      {
        id: "r-1",
        title: "Founding Backend Engineer",
        description: "Own the API and data layer. TypeScript/Node, Postgres.",
      },
      {
        id: "r-2",
        title: "Content & Community Lead",
        description: "Grow our founder community and learning content.",
      },
    ],
    createdAt: 1_700_000_000_000,
  },
  {
    id: "s-machi",
    ownerId: "u-tom",
    name: "Machi",
    industry: "Marketplace",
    description:
      "A hyperlocal marketplace connecting neighborhoods with trusted local service providers.",
    stage: "Pre-Seed",
    website: "https://machi.io",
    teamSize: 1,
    openRoles: [
      {
        id: "r-3",
        title: "Technical Co-Founder",
        description: "Lead all of engineering. Equity-heavy founding role.",
      },
    ],
    createdAt: 1_700_700_000_000,
  },
];

/**
 * Project board for Crewboot (s-xyz). Mix of statuses, assignees, and
 * priorities so progress tracking and the board render with real data.
 * Due dates are fixed 2026 timestamps so the demo reads sensibly.
 */
export const seedTasks: ProjectTask[] = [
  {
    id: "pt-1",
    startupId: "s-xyz",
    title: "Set up CI/CD pipeline",
    description: "GitHub Actions for lint, type-check, and preview deploys.",
    assigneeId: "u-jordan",
    status: "done",
    priority: "High",
    createdBy: "u-akshay",
    createdAt: 1_701_000_000_000,
  },
  {
    id: "pt-2",
    startupId: "s-xyz",
    title: "Launch referral program",
    description: "Double-sided referral with shareable invite links.",
    assigneeId: "u-liam",
    status: "done",
    priority: "Medium",
    createdBy: "u-akshay",
    createdAt: 1_701_010_000_000,
  },
  {
    id: "pt-3",
    startupId: "s-xyz",
    title: "Migrate auth to OAuth",
    description: "Google + GitHub sign-in, replace the mock login flow.",
    assigneeId: "u-jordan",
    status: "in-progress",
    priority: "High",
    dueDate: 1_781_913_600_000,
    createdBy: "u-akshay",
    createdAt: 1_701_020_000_000,
  },
  {
    id: "pt-4",
    startupId: "s-xyz",
    title: "Design system v2",
    description: "Token cleanup, dark-mode polish, and a component audit.",
    assigneeId: "u-mia",
    status: "in-progress",
    priority: "Medium",
    dueDate: 1_783_209_600_000,
    createdBy: "u-akshay",
    createdAt: 1_701_030_000_000,
  },
  {
    id: "pt-5",
    startupId: "s-xyz",
    title: "SEO content sprint",
    description: "Ten cornerstone articles targeting founder keywords.",
    assigneeId: "u-liam",
    status: "todo",
    priority: "Low",
    dueDate: 1_784_073_600_000,
    createdBy: "u-akshay",
    createdAt: 1_701_040_000_000,
  },
  {
    id: "pt-6",
    startupId: "s-xyz",
    title: "Customer interview round",
    description: "Talk to 15 founders about weekly workflow pain.",
    assigneeId: "u-akshay",
    status: "todo",
    priority: "Medium",
    dueDate: 1_783_209_600_000,
    createdBy: "u-akshay",
    createdAt: 1_701_050_000_000,
  },
  {
    id: "pt-7",
    startupId: "s-xyz",
    title: "Onboarding redesign",
    description: "Cut the wizard to three steps and add progress saving.",
    assigneeId: "u-mia",
    status: "todo",
    priority: "High",
    dueDate: 1_784_073_600_000,
    createdBy: "u-akshay",
    createdAt: 1_701_060_000_000,
  },
];

export const seedConversations: Conversation[] = [
  {
    id: "c-akshay-sarah",
    participantIds: ["u-akshay", "u-sarah"],
    createdAt: 1_701_000_000_000,
  },
  {
    id: "c-akshay-david",
    participantIds: ["u-akshay", "u-david"],
    createdAt: 1_701_100_000_000,
  },
];

export const seedMessages: Message[] = [
  {
    id: "m-1",
    conversationId: "c-akshay-sarah",
    senderId: "u-sarah",
    content:
      "Hi Akshay — saw Crewboot on Discover. The founder-tooling angle is interesting. What's your traction so far?",
    timestamp: 1_701_000_100_000,
  },
  {
    id: "m-2",
    conversationId: "c-akshay-sarah",
    senderId: "u-akshay",
    content:
      "Thanks Sarah! Early but promising — a few hundred founders on the waitlist and strong weekly retention on the dashboard.",
    timestamp: 1_701_000_200_000,
  },
  {
    id: "m-3",
    conversationId: "c-akshay-david",
    senderId: "u-david",
    content: "Happy to do office hours this week if useful. How's the team coming together?",
    timestamp: 1_701_100_100_000,
  },
];

export const seedJoinRequests: JoinRequest[] = [
  {
    id: "jr-priya",
    startupId: "s-xyz",
    requesterId: "u-priya",
    roleId: "r-frontend",
    roleTitle: "Frontend Developer",
    message:
      "Hi Akshay — I'd love to join Crewboot as your Frontend Developer. I've spent the last 4 years building product UIs in Next.js + TypeScript + Tailwind, and the founder-OS vision really resonates. I can own the web app end to end and care a lot about responsive, polished UX. Portfolio attached — happy to walk through past work.",
    status: "pending",
    createdAt: 1_701_200_000_000,
  },
  {
    id: "jr-marco",
    startupId: "s-xyz",
    requesterId: "u-marco",
    roleId: "r-frontend",
    roleTitle: "Frontend Developer",
    message:
      "Excited about Crewboot. Strong React/TypeScript background and a soft spot for design systems. Would love to help ship the dashboard and recruitment surfaces.",
    status: "pending",
    createdAt: 1_701_250_000_000,
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-akshay",
    type: "message",
    title: "New message from Sarah Chen",
    body: "Hi Akshay — saw Crewboot on Discover...",
    read: false,
    href: "/messages?c=c-akshay-sarah",
    timestamp: 1_701_000_100_000,
  },
  {
    id: "n-2",
    userId: "u-akshay",
    type: "system",
    title: "Complete your profile to stand out",
    body: "Startups with a full profile and skills get 3x more connection requests.",
    read: false,
    href: "/profile",
    timestamp: 1_701_050_000_000,
  },
  {
    id: "n-3",
    userId: "u-akshay",
    type: "message",
    title: "New message from David Park",
    body: "Happy to do office hours this week if useful...",
    read: true,
    href: "/messages?c=c-akshay-david",
    timestamp: 1_701_100_100_000,
  },
  {
    id: "n-4",
    userId: "u-akshay",
    type: "join_request",
    title: "Priya Sharma applied for Frontend Developer at Crewboot",
    body: "Hi Akshay — I'd love to join Crewboot as your Frontend Developer...",
    read: false,
    href: "/recruitment",
    timestamp: 1_701_200_000_000,
  },
  {
    id: "n-5",
    userId: "u-akshay",
    type: "join_request",
    title: "Marco Rossi applied for Frontend Developer at Crewboot",
    body: "Excited about Crewboot. Strong React/TypeScript background...",
    read: false,
    href: "/recruitment",
    timestamp: 1_701_250_000_000,
  },
];
